spring:
  datasource:
    url: jdbc:sqlserver://springboot-server.database.windows.net:1433;database=CRUD_Basic;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: springboot-server
    password: Thucu2001@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


